<?php

namespace Javleds\Traccar\Tests;

use Faker\Factory;
use Faker\Generator;
use Javleds\Traccar\Facades\Client;
use Javleds\Traccar\TraccarServiceProvider;
use Orchestra\Testbench\TestCase;

class BaseTestCase extends TestCase
{
    /**
     * @var Generator
     */
    public Generator $faker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
    }

    protected function getPackageProviders($app): array
    {
        return [
            TraccarServiceProvider::class,
        ];
    }

    protected function getPackageAliases($app): array
    {
        return [
            'Client' => Client::class,
        ];
    }
}
